language: node_js
node_js:
- '6'
install:
- npm install
- npm install -g codecov
script:
- npm run test:ci
- codecov
deploy:
  provider: npm
  email: maurizio.cas@gmail.com
  api_key:
    secure: mOKBUKhquWm42nYbXf3pr144KyG2KVqW0ldWXblVPm5U8ZIPCqMhmRUJD3M/fyeLVMoUoOlVXu1AhxTyFIi5y4TjH29joAC0ZnppI/vr+Ki4zcgHOzPuUHgthsxL8Ov40sJUPEg1oId7XXH5Dj5Y3+zNr4SqyN04F96NqLN+dVcHhDHrxdag0swdXyAIFloGXFJFGOABOH+MBq5InujyVfQ56a6iT8lAZDkzr6GkFGMuao4pavVny4bVehacIHrByYJq+To6zxn6/afqtWUNt6hpPqn02nvJcFSdamC69GNmwVGBDGe1ZYvBN2r3nYwIb+wJr0iBD0hCRQxdiXKpLjGdYUm9LMbz3ZWLYYOw49xZEsiQDAgumTSN4CwlyE1Ba3kgZhaqOilYEdqbUqWthOVDRCiLicza/MrnMhd0GYPUb+/fVrpfdYkCL3f11/APpYf03GKPXcHpVZmk+nKCM2XFMGmoePg6DYG7OqMKl5znie4n4MfvuEM1fsjJzj85xEceaWjNdQkee6VbkSoW+A3EFNS+tT1Be6VXaX8i8WwD7BiFg+s89rj0k4GX1gpTcu1SNJTI8KbL60ZPa8Gb+5CS8KFufVvXBy46vadWqwJ4/tfuA519GniNcQkMSfoL6q6BMwDJycTdITi9KmFkW2QU0XGUUZoHLqWZO7rxQDA=
  on:
    tags: true
